version: "3.0"
services:
  api_service:
    build: .
    restart: always
    ports:
      - 8091:8091
    depends_on:
      - mysql_db
    links:
      - mysql_db:app_db
  mysql_db:
    image: mysql/mysql-server:8.0.27
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: book_store
      MYSQL_USER: alain
      MYSQL_PASSWORD: aPTR1JS3nJIf6iB
      MYSQL_ROOT_PASSWORD: aPTR1JS3nJIf6iB