CREATE TABLE IF NOT EXISTS author (
id INTEGER NOT NULL AUTO_INCREMENT,
name  VARCHAR(100) NOT NULL,
created_date  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
modified_date  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS book (
id INTEGER NOT NULL AUTO_INCREMENT,
name  VARCHAR(100) NOT NULL,
type  VARCHAR(100) NOT NULL,
volume  INTEGER NOT NULL,
generation INTEGER NOT NULL,
author_id  INTEGER NOT NULL,
created_date  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
modified_date  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (id),
FOREIGN KEY (author_id) REFERENCES author(id)
);